insert into students (stid, name) VALUES (1, 'Moshe');
insert into students (stid, name) VALUES (2, 'Sara');
insert into students (stid, name) VALUES (3, 'Vasya');
insert into subjects (suid, subject) VALUES (1,'React');
insert into subjects (suid, subject) VALUES (2, 'Java');
insert into marks (id, mark, student_stid, subject_jpa_suid) VALUES (1, 90, 1, 1);
insert into marks (id, mark, student_stid, subject_jpa_suid) VALUES (2, 90, 1, 2);
insert into marks (id, mark, student_stid, subject_jpa_suid) VALUES (3, 80, 2, 1);
insert into marks (id, mark, student_stid, subject_jpa_suid) VALUES (4, 80, 2, 2);
insert into marks (id, mark, student_stid, subject_jpa_suid) VALUES (5, 40, 3, 2);